# Copyright Antmicro 2023
# SPDX-License-Identifier: Apache-2.0

CURDIR := $(abspath $(dir $(lastword $(MAKEFILE_LIST))))

SOURCES = ../crt0.S main.c
TARGET  = phy_calib

include $(CURDIR)/../common.mk

check:
	@:
