name: Verilator Build

on:
  workflow_call:

jobs:
  verilator:
    name: Build Verilator
    runs-on: ubuntu-latest
    env:
      TOOL_NAME: verilator
      TOOL_VERSION: v5.018
      DEBIAN_FRONTEND: "noninteractive"

    steps:
      - name: Setup Cache Metadata
        id: cache_metadata
        run: |
          cache_date=$(date +"%Y_%m_%d")
          cache_name=cache_${{ env.TOOL_NAME }}_${{ env.TOOL_VERSION }}
          echo "Cache date: "$cache_date
          echo "Cache name: "$cache_name
          echo "cache_date=$cache_date" >> "$GITHUB_ENV"
          echo "cache_name=$cache_name" >> "$GITHUB_ENV"

      - name: Setup cache
        uses: actions/cache@v3
        id: cache
        timeout-minutes: 60
        with:
          path: |
            /opt/verilator
            /opt/verilator/.cache
          key: ${{ env.cache_name }}_${{ env.cache_date }}
          restore-keys: ${{ env.cache_name }}_

      - name: Install prerequisities
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: |
          sudo apt -qqy update && sudo apt -qqy --no-install-recommends install \
          autoconf automake autotools-dev \
          bc bison build-essential \
          ccache curl \
          flex \
          gawk git gperf \
          help2man \
          libexpat-dev libfl-dev libfl2 libgmp-dev \
          libmpc-dev libmpfr-dev libtool \
          ninja-build \
          patchutils python3 python3-pip \
          texinfo \
          zlib1g zlib1g-dev

      - name: Build Verilator
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: |
          export CCACHE_DIR=/opt/verilator/.cache
          ccache --show-config | grep cache_dir
          git clone https://github.com/verilator/verilator
          pushd verilator
            git checkout ${{ env.TOOL_VERSION }}
            autoconf
            ./configure --prefix=/opt/verilator
            make -j `nproc`
            make install
          popd
